- name: stop ec2
  hosts: localhost
  connection: local
  gather_facts: False

  vars:
      region: ap-northeast-1
      aws_access_key_id: AKIAIWXUO632R2XVVVDQ
      aws_secret_access_key: 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
  
  tasks:
    - name: stoping
      ec2:
        region: "{{ region }}"
        aws_access_key: "{{aws_access_key_id}}"
        aws_secret_key: "{{aws_secret_access_key}}"
        instance_ids: i-07d8da9f282c4d5c1
        state: stopped
        wait: True
